'''
This script shows how we can load the SavedModel generated by running the train_mnist.py script
directly to a Keras model and make predictions just by calling its predict() method.
'''


import os

import numpy as np
import tensorflow as tf
from tensorflow import keras

# Load the trained model 
cwd = os.getcwd()
model_path = f'{cwd}/my_mnist_model/0001'
model = keras.models.load_model(model_path)

# Import the Fashion MNIST dataset
(X_train_full, y_train_full), (X_test, y_test) = keras.datasets.mnist.load_data()
# Scale the values to 0.0 to 1.0
X_train_full = X_train_full[..., np.newaxis].astype(np.float32) / 255.
X_test = X_test[..., np.newaxis].astype(np.float32) / 255.
# Take 3 examples from the test data to make predictions
X_new = X_test[:3]
# Get predictions
y_pred = model.predict(tf.constant(X_new, dtype=tf.float32))